# UMUD challenge Kaggle kernel: unpacks the repo, links the competition data
# and runs one script from kaggle/runs/ (which writes its own outputs to
# /kaggle/working). Generated by kaggle/build_kernel.py -- the repo is
# embedded below as a tarball.
import base64
import io
import subprocess
import sys
import tarfile
from pathlib import Path

REPO_TGZ_B64 = "__REPO_TGZ_B64__"
RUN_SCRIPT = "__RUN_SCRIPT__"
EXTRA_ARGS = __EXTRA_ARGS__

WORK = Path("/kaggle/working")
REPO = Path("/kaggle/tmp/umud")
DATA_DIRS = ["apo_imgs_v1", "apo_masks_v1", "fasc_imgs_v1", "fasc_masks_v1", "test_images_v2"]


def run(cmd: list[str]) -> None:
    print("+", " ".join(cmd), flush=True)
    subprocess.run(cmd, cwd=REPO, check=True)


REPO.mkdir(parents=True, exist_ok=True)
with tarfile.open(fileobj=io.BytesIO(base64.b64decode(REPO_TGZ_B64)), mode="r:gz") as tf:
    tf.extractall(REPO)

data_root = next(p.parent for p in Path("/kaggle/input").rglob("apo_imgs_v1") if p.is_dir())
print("data root:", data_root)
for name in DATA_DIRS:
    (REPO / name).symlink_to(data_root / name)

run([sys.executable, "-m", "pip", "install", "-q", "segmentation-models-pytorch", "tifffile", "imagecodecs", "albumentations", "scikit-image"])
run([sys.executable, "-m", "pip", "install", "-q", "--no-deps", "-e", "."])
run(["nvidia-smi"])

run(["bash", RUN_SCRIPT, *EXTRA_ARGS])
print("outputs:", sorted(str(p.relative_to(WORK)) for p in WORK.rglob("*") if p.is_file()))
